apiVersion: v1
kind: Service
metadata:
  name: approval2
  namespace: default
  labels:
    SERVICENAME: approval2
  annotations:
    build: "1.5"
    builder: "buildbot"
spec:
  type: ClusterIP
  selector:
    SERVICENAME: approval2
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
